trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'sonarqube'  # Replace with your SonarQube service connection name
      scannerMode: 'Maven'
      configMode: 'manual'
      cliProjectKey: 'azure-devops'
      cliProjectName: 'azure-devops'
      extraProperties: |
        sonar.projectKey=azure-devops
        sonar.projectName=azure-devops

  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true

  - task: Maven@3
    inputs:
      mavenPomFile: 'sonarqube/sonarqubespring/pom.xml'
      goals: 'clean install sonar:sonar'
      codeAnalysisEnabled: true
      codeCoverageToolOption: 'None'

  # Add additional build and deployment tasks as required
